networks:
  backend:

services:
  uv-app:
    build: 
      context: ../
      dockerfile: ./docker/uv-app/Dockerfile
    env_file:
      - ../.env
    depends_on:
      - db
      - redis
    volumes:
      - ../:/code
    networks:
      - backend
    
  db:
    image: postgres:16-alpine
    volumes:
     - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    networks:
      - backend

  nginx:
    image: nginx:1.28.0-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/certs:/etc/nginx/certs
    depends_on:
      - uv-app
    networks:
      - backend

  redis:
    image: redis:7.4-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ../redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    networks:
      - backend

volumes:
  postgres_data:
  redis-data:



